export const REGISTER_USERS = 'REGISTER_USERS'
export const RECIEVED_REGISTER_USERS = 'RECIEVED_REGISTER_USERS'
export const FAILURE_REGISTER_USERS = 'FAILURE_REGISTER_USERS'

export const SIGNIN_USERS = 'SIGNIN_USERS'
export const RECIEVED_SIGNIN_USERS = 'RECIEVED_SIGNIN_USERS'
export const FAILURE_SIGNIN_USERS = 'FAILURE_SIGNIN_USERS'

export const GET_USER = 'GET_USER'
export const RECIEVED_GET_USER = 'RECIEVED_GET_USER'
export const FAILURE_GET_USER = 'FAILURE_GET_USER'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const RECIEVED_GET_CATEGORIES = 'RECIEVED_GET_CATEGORIES'
export const FAILURE_GET_CATEGORIES = 'FAILURE_GET_CATEGORIES'

export const CREATE_BLOG = 'CREATE_BLOG'
export const RECIEVED_CREATE_BLOG = 'RECIEVED_CREATE_BLOG'
export const FAILURE_CREATE_BLOG = 'FAILURE_CREATE_BLOG'

export const GET_USER_BLOGS = 'GET_USER_BLOGS'
export const RECIEVED_GET_USER_BLOGS = 'RECIEVED_GET_USER_BLOGS'
export const FAILURE_GET_USER_BLOGS = 'FAILURE_GET_USER_BLOGS'

export const GET_BLOG_BY_ID = 'GET_BLOG_BY_ID'
export const RECIEVED_GET_BLOG_BY_ID = 'RECIEVED_GET_BLOG_BY_ID'
export const FAILURE_GET_BLOG_BY_ID = 'FAILURE_GET_BLOG_BY_ID'

export const UPDATE_BLOG = 'UPDATE_BLOG'
export const RECIEVED_UPDATE_BLOG = 'RECIEVED_UPDATE_BLOG'
export const FAILURE_UPDATE_BLOG = 'FAILURE_UPDATE_BLOG'

export const DELETE_BLOG = 'DELETE_BLOG'
export const RECIEVED_DELETE_BLOG = 'RECIEVED_DELETE_BLOG'
export const FAILURE_DELETE_BLOG = 'FAILURE_DELETE_BLOG'

export const GET_BLOGS = 'GET_BLOGS'
export const RECIEVED_GET_BLOGS = 'RECIEVED_GET_BLOGS'
export const FAILURE_GET_BLOGS = 'FAILURE_GET_BLOGS'